FROM golang:1.17 AS build-env
RUN go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /tmp
RUN git clone -b 1.13.2 https://github.com/istio/istio.git
RUN cd istio/pilot/cmd/pilot-discovery && go build -gcflags="all=-N -l" -o /tmp/pilot-discovery


FROM istio/proxyv2:1.13.2-debug
WORKDIR /
COPY --from=build-env /go/bin/dlv /tmp/pilot-discovery /usr/bin/

ENTRYPOINT ["/usr/bin/pilot-discovery"]
