FROM golang:1.17 AS build-env
RUN go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /tmp
RUN git clone -b 1.13.2 https://github.com/istio/istio.git
RUN cd istio/pilot/cmd/pilot-agent && go build -gcflags="all=-N -l" -o /tmp/pilot-agent


FROM istio/proxyv2:1.13.2-debug
WORKDIR /
COPY --from=build-env /go/bin/dlv /tmp/pilot-agent /usr/bin/

ENTRYPOINT ["dlv --listen=:5432 --headless=true exec /usr/bin/pilot-agent --"]


