FROM golang:1.17 AS build-env
RUN go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /tmp
RUN git clone -b 1.13.2 https://github.com/istio/istio.git
RUN go build -gcflags="all=-N -l" istio/pilot/cmd/pilot-discovery


FROM istio/proxyv2:1.13.2-debug
WORKDIR /
COPY --from=build-env /go/bin/dlv /usr/bin/dlv
RUN rm -f /usr/bin/pilot-discovery
COPY --from=build-env /tmp/pilot-discovery /usr/bin/pilot-discovery
